# Generated by Django 3.1.14 on 2023-12-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20231217_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('0', 'ユーザー'), ('1', 'スタッフ')], default='1', max_length=1),
        ),
    ]
