# Generated by Django 3.1.14 on 2023-12-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('0', 'カスタマー'), ('1', 'スタッフ')], default='1', max_length=1),
        ),
    ]
